import { createJsDelivrUrl } from "../../resources/jsdelivr";
import type { Resource } from "../../../types/resource";

export const inWorldLivingLabResources = [
  {
    id: "iwll-in-world-persona-sheet",
    courseSlug: "in-world-living-lab",
    type: "download",
    title: "In-World Persona Sheet",
    summary: "A worksheet for designing the test persona for daily-life simulation.",
    url: createJsDelivrUrl("/in-world-living-lab/resources/in-world-persona-sheet.md"),
    filename: "in-world-persona-sheet.md",
  },
  {
    id: "iwll-simulation-zone-sheet",
    courseSlug: "in-world-living-lab",
    type: "download",
    title: "Simulation Zone Sheet",
    summary: "A worksheet for bounding the location and available interactions.",
    url: createJsDelivrUrl("/in-world-living-lab/resources/simulation-zone-sheet.md"),
    filename: "simulation-zone-sheet.md",
  },
  {
    id: "iwll-daily-routine-template",
    courseSlug: "in-world-living-lab",
    type: "download",
    title: "Daily Routine Template",
    summary: "A template for planning an ordinary in-world day.",
    url: createJsDelivrUrl("/in-world-living-lab/resources/daily-routine-template.md"),
    filename: "daily-routine-template.md",
  },
  {
    id: "iwll-constraint-sheet",
    courseSlug: "in-world-living-lab",
    type: "download",
    title: "Constraint Sheet",
    summary: "A worksheet for connecting constraints to choices and lore signals.",
    url: createJsDelivrUrl("/in-world-living-lab/resources/constraint-sheet.md"),
    filename: "constraint-sheet.md",
  },
  {
    id: "iwll-daily-journal-template",
    courseSlug: "in-world-living-lab",
    type: "download",
    title: "Daily Journal Template",
    summary: "A journal template for capturing experience and creator notes.",
    url: createJsDelivrUrl("/in-world-living-lab/resources/daily-journal-template.md"),
    filename: "daily-journal-template.md",
  },
  {
    id: "iwll-weekly-review-template",
    courseSlug: "in-world-living-lab",
    type: "download",
    title: "Weekly Review Template",
    summary: "A review worksheet for extracting discoveries and contradictions.",
    url: createJsDelivrUrl("/in-world-living-lab/resources/weekly-review-template.md"),
    filename: "weekly-review-template.md",
  },
  {
    id: "iwll-social-interaction-log",
    courseSlug: "in-world-living-lab",
    type: "download",
    title: "Social Interaction Log",
    summary: "A log for tracking status, etiquette, and consequences.",
    url: createJsDelivrUrl("/in-world-living-lab/resources/social-interaction-log.md"),
    filename: "social-interaction-log.md",
  },
  {
    id: "iwll-cost-of-living-sheet",
    courseSlug: "in-world-living-lab",
    type: "download",
    title: "Cost of Living Sheet",
    summary: "A worksheet for modeling daily cost, access, and scarcity.",
    url: createJsDelivrUrl("/in-world-living-lab/resources/cost-of-living-sheet.md"),
    filename: "cost-of-living-sheet.md",
  },
  {
    id: "iwll-law-risk-sheet",
    courseSlug: "in-world-living-lab",
    type: "download",
    title: "Law Risk Sheet",
    summary: "A worksheet for legal, social, and practical risk.",
    url: createJsDelivrUrl("/in-world-living-lab/resources/law-risk-sheet.md"),
    filename: "law-risk-sheet.md",
  },
  {
    id: "iwll-lore-extraction-table",
    courseSlug: "in-world-living-lab",
    type: "download",
    title: "Lore Extraction Table",
    summary: "A table for turning journal signals into canon and revision tasks.",
    url: createJsDelivrUrl("/in-world-living-lab/resources/lore-extraction-table.md"),
    filename: "lore-extraction-table.md",
  },
  {
    id: "iwll-realism-review-sheet",
    courseSlug: "in-world-living-lab",
    type: "download",
    title: "Realism Review Sheet",
    summary: "A review sheet for identifying vague or implausible simulation details.",
    url: createJsDelivrUrl("/in-world-living-lab/resources/realism-review-sheet.md"),
    filename: "realism-review-sheet.md",
  },
  {
    id: "iwll-journal-to-art-pipeline",
    courseSlug: "in-world-living-lab",
    type: "download",
    title: "Journal to Art Pipeline",
    summary: "A template for converting journal evidence into visual direction.",
    url: createJsDelivrUrl("/in-world-living-lab/resources/journal-to-art-pipeline.md"),
    filename: "journal-to-art-pipeline.md",
  },
  {
    id: "iwll-30-day-in-world-living-prompts",
    courseSlug: "in-world-living-lab",
    type: "download",
    title: "30-Day In-World Living Prompts",
    summary: "A prompt sequence for extending the simulation into a month-long practice.",
    url: createJsDelivrUrl("/in-world-living-lab/resources/30-day-in-world-living-prompts.md"),
    filename: "30-day-in-world-living-prompts.md",
  },
] as const satisfies readonly Resource[];
