import { createJsDelivrUrl } from "../../resources/jsdelivr";
import type { Resource } from "../../../types/resource";

export const worldbuildingOperatingSystemResources = [
  {
    id: "wos-project-seed-template",
    courseSlug: "worldbuilding-operating-system",
    type: "download",
    title: "Project Seed Template",
    summary: "A lightweight worksheet for turning a raw idea into a project seed.",
    url: createJsDelivrUrl("/worldbuilding-operating-system/resources/project-seed-template.md"),
    filename: "project-seed-template.md",
  },
  {
    id: "wos-creative-pillars-template",
    courseSlug: "worldbuilding-operating-system",
    type: "download",
    title: "Creative Pillars Template",
    summary: "A worksheet for defining creative pillars and decision filters.",
    url: createJsDelivrUrl(
      "/worldbuilding-operating-system/resources/creative-pillars-template.md",
    ),
    filename: "creative-pillars-template.md",
  },
  {
    id: "wos-scope-control-sheet",
    courseSlug: "worldbuilding-operating-system",
    type: "download",
    title: "Scope Control Sheet",
    summary: "A worksheet for defining version boundaries and a parking lot.",
    url: createJsDelivrUrl("/worldbuilding-operating-system/resources/scope-control-sheet.md"),
    filename: "scope-control-sheet.md",
  },
  {
    id: "wos-world-laws-sheet",
    courseSlug: "worldbuilding-operating-system",
    type: "download",
    title: "World Laws Sheet",
    summary: "A worksheet for connecting world rules to practical consequences.",
    url: createJsDelivrUrl("/worldbuilding-operating-system/resources/world-laws-sheet.md"),
    filename: "world-laws-sheet.md",
  },
  {
    id: "wos-civilization-canvas",
    courseSlug: "worldbuilding-operating-system",
    type: "download",
    title: "Civilization Canvas",
    summary: "A worksheet for modeling needs, power, institutions, and pressures.",
    url: createJsDelivrUrl("/worldbuilding-operating-system/resources/civilization-canvas.md"),
    filename: "civilization-canvas.md",
  },
  {
    id: "wos-culture-sheet",
    courseSlug: "worldbuilding-operating-system",
    type: "download",
    title: "Culture Sheet",
    summary: "A worksheet for culture values, customs, taboos, symbols, and tensions.",
    url: createJsDelivrUrl("/worldbuilding-operating-system/resources/culture-sheet.md"),
    filename: "culture-sheet.md",
  },
  {
    id: "wos-timeline-anchor-sheet",
    courseSlug: "worldbuilding-operating-system",
    type: "download",
    title: "Timeline Anchor Sheet",
    summary: "A worksheet for history anchors that affect the present.",
    url: createJsDelivrUrl("/worldbuilding-operating-system/resources/timeline-anchor-sheet.md"),
    filename: "timeline-anchor-sheet.md",
  },
  {
    id: "wos-faction-sheet",
    courseSlug: "worldbuilding-operating-system",
    type: "download",
    title: "Faction Sheet",
    summary: "A worksheet for faction goals, resources, fears, and rivals.",
    url: createJsDelivrUrl("/worldbuilding-operating-system/resources/faction-sheet.md"),
    filename: "faction-sheet.md",
  },
  {
    id: "wos-character-world-link-sheet",
    courseSlug: "worldbuilding-operating-system",
    type: "download",
    title: "Character World Link Sheet",
    summary: "A worksheet for connecting characters to world systems.",
    url: createJsDelivrUrl(
      "/worldbuilding-operating-system/resources/character-world-link-sheet.md",
    ),
    filename: "character-world-link-sheet.md",
  },
  {
    id: "wos-canon-bible-outline",
    courseSlug: "worldbuilding-operating-system",
    type: "download",
    title: "Canon Bible Outline",
    summary: "A starter outline for organizing canon, drafts, and open questions.",
    url: createJsDelivrUrl("/worldbuilding-operating-system/resources/canon-bible-outline.md"),
    filename: "canon-bible-outline.md",
  },
  {
    id: "wos-decision-log-template",
    courseSlug: "worldbuilding-operating-system",
    type: "download",
    title: "Decision Log Template",
    summary: "A template for tracking worldbuilding decisions and follow-up effects.",
    url: createJsDelivrUrl("/worldbuilding-operating-system/resources/decision-log-template.md"),
    filename: "decision-log-template.md",
  },
  {
    id: "wos-continuity-checklist",
    courseSlug: "worldbuilding-operating-system",
    type: "download",
    title: "Continuity Checklist",
    summary: "A checklist for catching contradictions before new material becomes canon.",
    url: createJsDelivrUrl("/worldbuilding-operating-system/resources/continuity-checklist.md"),
    filename: "continuity-checklist.md",
  },
  {
    id: "wos-30-day-workflow-planner",
    courseSlug: "worldbuilding-operating-system",
    type: "download",
    title: "30-Day Workflow Planner",
    summary: "A planner for pacing worldbuilding work across a month.",
    url: createJsDelivrUrl("/worldbuilding-operating-system/resources/30-day-workflow-planner.md"),
    filename: "30-day-workflow-planner.md",
  },
] as const satisfies readonly Resource[];
